"""Dynamic office matching from PostgreSQL ``offices`` + ``office_aliases``.

Article Planner and review grouping must call this instead of hardcoding
institution-specific office names or abbreviations.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from functools import lru_cache
from typing import Any

from sqlalchemy.orm import Session

from app.models.db_models import Office, OfficeAlias

# Only accept an office label when match confidence is clearly dominant.
_MIN_CONFIDENCE = 0.72
_AMBIGUITY_MARGIN = 0.12


@dataclass(frozen=True)
class OfficeMatch:
    office_id: str
    office_name: str
    service_category: str | None
    matched_alias: str
    weight: float
    confidence: float


def _normalize_text(value: str | None) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip().lower()


def _alias_pattern(alias: str) -> re.Pattern[str]:
    escaped = re.escape(alias.strip())
    # Prefer whole-word / phrase matches so short aliases do not overfire.
    return re.compile(rf"(?<![A-Za-z0-9]){escaped}(?![A-Za-z0-9])", flags=re.I)


def _load_alias_rows(session: Session) -> list[dict[str, Any]]:
    rows = (
        session.query(OfficeAlias, Office)
        .join(Office, OfficeAlias.office_id == Office.id)
        .filter(OfficeAlias.is_active.is_(True))
        .all()
    )
    payload: list[dict[str, Any]] = []
    for alias_row, office in rows:
        alias = str(alias_row.alias or "").strip()
        if not alias:
            continue
        payload.append(
            {
                "alias": alias,
                "weight": float(alias_row.weight or 1.0),
                "office_id": office.id,
                "office_name": office.name,
                "service_category": office.service_category,
            }
        )
    # Longer aliases first so "Office of Student Affairs" wins over "Office".
    payload.sort(key=lambda item: (-len(item["alias"]), -item["weight"]))
    return payload


@lru_cache(maxsize=1)
def _cached_alias_snapshot(cache_key: str) -> tuple[dict[str, Any], ...]:
    # cache_key forces refresh when caller wants; default key is regenerated by clear.
    return tuple()


def load_office_aliases(session: Session) -> list[dict[str, Any]]:
    """Load active aliases joined to offices. Safe to call repeatedly."""
    try:
        return _load_alias_rows(session)
    except Exception:
        # Table may not exist yet; roll back so the session stays usable.
        try:
            session.rollback()
        except Exception:
            pass
        return []


def clear_office_alias_cache() -> None:
    _cached_alias_snapshot.cache_clear()


def match_office_from_text(text: str, db: Session | None) -> OfficeMatch | None:
    """Return a high-confidence office match from ``office_aliases``, or None.

    Rules:
    - Match aliases dynamically from PostgreSQL (joined to ``offices``).
    - Score with alias weight and relative match length.
    - Return an office only when confidence is high and not ambiguous.
    - Never invent office names when aliases are missing/weak.
    """
    if db is None:
        return None
    haystack = _normalize_text(text)
    if not haystack:
        return None

    aliases = load_office_aliases(db)
    if not aliases:
        return None

    scored: dict[str, dict[str, Any]] = {}
    for row in aliases:
        alias = row["alias"]
        pattern = _alias_pattern(alias)
        if not pattern.search(haystack):
            continue
        office_id = row["office_id"]
        weight = max(0.1, float(row["weight"] or 1.0))
        # Longer aliases relative to text are stronger evidence.
        length_boost = min(1.0, len(alias) / max(12.0, min(len(haystack), 80)))
        score = weight * (0.65 + 0.35 * length_boost)
        current = scored.get(office_id)
        if current is None or score > current["score"]:
            scored[office_id] = {
                "office_id": office_id,
                "office_name": row["office_name"],
                "service_category": row["service_category"],
                "matched_alias": alias,
                "weight": weight,
                "score": score,
            }

    if not scored:
        return None

    ranked = sorted(scored.values(), key=lambda item: item["score"], reverse=True)
    best = ranked[0]
    second = ranked[1] if len(ranked) > 1 else None

    confidence = min(1.0, float(best["score"]) / 1.35)
    if confidence < _MIN_CONFIDENCE:
        return None
    if second is not None:
        second_confidence = min(1.0, float(second["score"]) / 1.35)
        if confidence - second_confidence < _AMBIGUITY_MARGIN:
            return None

    return OfficeMatch(
        office_id=str(best["office_id"]),
        office_name=str(best["office_name"]),
        service_category=(str(best["service_category"]).strip() or None)
        if best.get("service_category")
        else None,
        matched_alias=str(best["matched_alias"]),
        weight=float(best["weight"]),
        confidence=confidence,
    )
