"""Prepare secrets, TLS, seeds, and Flutter signing for campus-style deploy.

Run from repo root:
    python scripts/bootstrap_campus_deploy.py

Writes credentials ONLY to deploy/BOOTSTRAP_CREDENTIALS.txt (gitignored).
Keeps backend/.env for daily dev; production values go to backend/.env.production.
"""

from __future__ import annotations

import argparse
import os
import re
import secrets
import shutil
import string
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
OPENSSL = Path(r"C:\Program Files\Git\usr\bin\openssl.exe")
KEYTOOL = Path(r"C:\Program Files\Eclipse Adoptium\jre-8.0.372.7-hotspot\bin\keytool.exe")


def _read_dotenv(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        out[key.strip()] = value.strip()
    return out


def _password(length: int = 20) -> str:
    alphabet = string.ascii_letters + string.digits + "!@$%*"
    while True:
        value = "".join(secrets.choice(alphabet) for _ in range(length))
        if re.search(r"[A-Za-z]", value) and re.search(r"\d", value):
            return value


def _secret(nbytes: int = 48) -> str:
    return secrets.token_urlsafe(nbytes)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--public-origin", default="https://aska.local")
    parser.add_argument("--admin-email", default="admin@aska.local")
    parser.add_argument("--skip-seed", action="store_true")
    parser.add_argument("--skip-keystore", action="store_true")
    parser.add_argument(
        "--apply-production-env",
        action="store_true",
        help="Copy .env.production over backend/.env (default: leave daily-dev .env).",
    )
    args = parser.parse_args()

    existing = _read_dotenv(BACKEND / ".env")
    dev_bak = BACKEND / ".env.development.bak"
    if (BACKEND / ".env").is_file() and not dev_bak.is_file():
        shutil.copy2(BACKEND / ".env", dev_bak)
        print("Backed up backend/.env -> .env.development.bak")

    # Import after path setup so we share the same placeholder rules as the API.
    sys.path.insert(0, str(BACKEND))
    from app.config import is_placeholder_secret  # noqa: E402

    auth_secret = existing.get("ASKA_AUTH_SECRET_KEY", "").strip()
    if is_placeholder_secret(auth_secret):
        auth_secret = _secret(48)

    groq_key = existing.get("ASKA_GROQ_API_KEY", "").strip()
    db_url = existing.get("ASKA_DATABASE_URL") or (
        "postgresql+psycopg://postgres:aska1234@localhost:5432/aska_piyu"
    )
    test_db = existing.get("ASKA_TEST_DATABASE_URL") or (
        "postgresql+psycopg://postgres:aska1234@localhost:5432/aska_piyu_test"
    )
    kb_paths = existing.get("ASKA_KB_REBUILD_DOCUMENT_PATHS") or (
        "./data/documents/d9bf05ce-fcab-4629-ad4c-4f869481189f/LSPU Student Handbook.pdf;"
        "./data/documents/c67bd8c8-81cd-4c8c-bda1-4f7d2039a406/LSPU Faculty Manual 2020.pdf;"
        "./data/documents/6c3d0f00-fd53-43be-943f-09e1e7ddbce4/"
        "Laguna State Polytechnic University-CC_2026-1st Edition.pdf"
    )
    groq_model = existing.get("ASKA_GROQ_MODEL") or "llama-3.3-70b-versatile"

    postgres_password = _password(28)
    admin_password = _password(18)
    office_password = _password(18)
    keystore_password = _password(24)
    signup_invite = "ASKA-" + secrets.token_urlsafe(12)
    backup_passphrase = secrets.token_urlsafe(32)
    public_origin = args.public_origin.rstrip("/")
    admin_email = args.admin_email.strip().lower()

    (ROOT / ".env").write_text(
        "\n".join(
            [
                "# Generated by scripts/bootstrap_campus_deploy.py — do not commit.",
                f"POSTGRES_PASSWORD={postgres_password}",
                "HTTP_PORT=80",
                "HTTPS_PORT=443",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print("Wrote root .env")

    if public_origin == "https://aska.local":
        cors = '["https://aska.local"]'
    else:
        cors = f'["https://aska.local","{public_origin}"]'

    prod_env = BACKEND / ".env.production"
    prod_env.write_text(
        "\n".join(
            [
                "ASKA_CHROMA_PERSIST_DIR=./data/chroma",
                "ASKA_CHROMA_COLLECTION_NAME=aska_knowledge_base",
                "ASKA_RAG_TOP_K=5",
                f"ASKA_KB_REBUILD_DOCUMENT_PATHS={kb_paths}",
                "",
                "ASKA_ENV=production",
                f"ASKA_DATABASE_URL={db_url}",
                f"ASKA_TEST_DATABASE_URL={test_db}",
                "ASKA_ALLOW_DESTRUCTIVE_RESET=false",
                "ASKA_DOCUMENTS_PERSIST_DIR=./data/documents",
                "ASKA_TICKET_ATTACHMENTS_DIR=./data/ticket_attachments",
                "ASKA_DATABASE_INIT_ON_STARTUP=false",
                "",
                f"ASKA_AUTH_SECRET_KEY={auth_secret}",
                "ASKA_AUTH_TOKEN_TTL_MINUTES=480",
                "",
                "ASKA_ALLOW_ADMIN_API_KEY=false",
                "",
                f"ASKA_GROQ_API_KEY={groq_key}",
                f"ASKA_GROQ_MODEL={groq_model}",
                "ASKA_GROQ_TIMEOUT_SECONDS=30",
                "",
                f"ASKA_CORS_ORIGINS={cors}",
                "ASKA_TRUST_PROXY=true",
                "",
                f"ASKA_SEED_ADMIN_EMAIL={admin_email}",
                f"ASKA_SEED_ADMIN_PASSWORD={admin_password}",
                "ASKA_SEED_ADMIN_NAME=ASKa Admin",
                f"ASKA_SEED_OFFICE_PASSWORD={office_password}",
                "",
                "# LAB ONLY — do not expose HTTP :8080 on the public internet",
                "ASKA_ALLOW_PUBLIC_SIGNUP=true",
                "ASKA_SIGNUP_ALLOWED_EMAIL_DOMAINS=lspu.edu.ph,aska.local",
                f"ASKA_SIGNUP_INVITE_CODE={signup_invite}",
                f"ASKA_BACKUP_PASSPHRASE={backup_passphrase}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print("Wrote backend/.env.production")

    if not groq_key:
        print("WARNING: ASKA_GROQ_API_KEY is empty — check_production_env will fail.")

    cred = ROOT / "deploy" / "BOOTSTRAP_CREDENTIALS.txt"
    cred.write_text(
        "\n".join(
            [
                f"ASKa-Piyu bootstrap credentials — KEEP PRIVATE — {datetime.now(timezone.utc).isoformat()}",
                f"Public origin: {public_origin}",
                "",
                "Admin login:",
                f"  email:    {admin_email}",
                f"  password: {admin_password}",
                "",
                "Office logins (examples): registrar@aska.local, ict@aska.local, osas@aska.local",
                f"  password: {office_password}",
                "",
                "Student signup policy:",
                "  domains:     lspu.edu.ph,aska.local",
                f"  invite code: {signup_invite}",
                "",
                "Docker Postgres (root .env):",
                f"  POSTGRES_PASSWORD={postgres_password}",
                "",
                "Backup encryption passphrase:",
                f"  ASKA_BACKUP_PASSPHRASE={backup_passphrase}",
                "",
                "Android keystore (flutter_app/android/upload-keystore.jks):",
                f"  storePassword / keyPassword: {keystore_password}",
                "  keyAlias: aska-piyu",
                "",
                "WARNING: Lab / laptop only. Do NOT publish docker-compose HTTP :8080 publicly.",
                "TLS: deploy/certs/fullchain.pem + privkey.pem (self-signed for aska.local)",
                f"Flutter API: flutter_app/api_base.url -> {public_origin}",
                "",
                "On the campus VPS, replace aska.local with your real hostname + Lets Encrypt certs,",
                "update ASKA_CORS_ORIGINS and api_base.url, then compose with the https overlay.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print("Wrote deploy/BOOTSTRAP_CREDENTIALS.txt")
    (ROOT / "deploy" / "BACKUP_PASSPHRASE.txt").write_text(
        "\n".join(
            [
                "# ASKa-Piyu backup encryption passphrase — KEEP PRIVATE",
                backup_passphrase,
                "",
            ]
        ),
        encoding="utf-8",
    )
    print("Wrote deploy/BACKUP_PASSPHRASE.txt")

    if not OPENSSL.is_file():
        print(f"ERROR: OpenSSL not found at {OPENSSL}", file=sys.stderr)
        return 1

    cert_dir = ROOT / "deploy" / "certs"
    cert_dir.mkdir(parents=True, exist_ok=True)
    cnf = cert_dir / "aska.local.cnf"
    cnf.write_text(
        "\n".join(
            [
                "[req]",
                "default_bits = 2048",
                "prompt = no",
                "default_md = sha256",
                "distinguished_name = dn",
                "x509_extensions = v3_req",
                "",
                "[dn]",
                "CN = aska.local",
                "O = LSPU ASKa-Piyu",
                "C = PH",
                "",
                "[v3_req]",
                "subjectAltName = @alt_names",
                "basicConstraints = CA:FALSE",
                "keyUsage = digitalSignature, keyEncipherment",
                "extendedKeyUsage = serverAuth",
                "",
                "[alt_names]",
                "DNS.1 = aska.local",
                "DNS.2 = localhost",
                "IP.1 = 127.0.0.1",
                "",
            ]
        ),
        encoding="ascii",
    )
    subprocess.run(
        [
            str(OPENSSL),
            "req",
            "-x509",
            "-nodes",
            "-newkey",
            "rsa:2048",
            "-keyout",
            str(cert_dir / "privkey.pem"),
            "-out",
            str(cert_dir / "fullchain.pem"),
            "-days",
            "825",
            "-config",
            str(cnf),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
    )
    cnf.unlink(missing_ok=True)
    print("Wrote self-signed TLS certs for aska.local")

    (ROOT / "flutter_app" / "api_base.url").write_text(public_origin, encoding="ascii")
    print("Wrote flutter_app/api_base.url")

    if not args.skip_keystore:
        android = ROOT / "flutter_app" / "android"
        jks = android / "upload-keystore.jks"
        if not KEYTOOL.is_file():
            print(f"WARNING: keytool not found at {KEYTOOL}; skipping keystore")
        else:
            if jks.is_file():
                print("Keystore already exists; leaving in place")
            else:
                subprocess.run(
                    [
                        str(KEYTOOL),
                        "-genkeypair",
                        "-v",
                        "-keystore",
                        str(jks),
                        "-storetype",
                        "JKS",
                        "-keyalg",
                        "RSA",
                        "-keysize",
                        "2048",
                        "-validity",
                        "10000",
                        "-alias",
                        "aska-piyu",
                        "-storepass",
                        keystore_password,
                        "-keypass",
                        keystore_password,
                        "-dname",
                        "CN=ASKa-Piyu, OU=LSPU, O=LSPU, L=Siniloan, ST=Laguna, C=PH",
                    ],
                    check=True,
                )
                print("Created flutter_app/android/upload-keystore.jks")
            (android / "key.properties").write_text(
                "\n".join(
                    [
                        f"storePassword={keystore_password}",
                        f"keyPassword={keystore_password}",
                        "keyAlias=aska-piyu",
                        "storeFile=upload-keystore.jks",
                        "",
                    ]
                ),
                encoding="ascii",
            )
            print("Wrote flutter_app/android/key.properties")

    daily_env = BACKEND / ".env"
    restore_daily = False
    tmp_bak: Path | None = None
    if args.apply_production_env:
        shutil.copy2(prod_env, daily_env)
        print("Applied .env.production -> backend/.env")
    else:
        tmp_bak = BACKEND / ".env.bootstrap.tmp"
        shutil.copy2(daily_env, tmp_bak)
        shutil.copy2(prod_env, daily_env)
        restore_daily = True
        print("Temporarily using .env.production for check/seed")

    env = os.environ.copy()
    env["PYTHONPATH"] = str(BACKEND)
    env["ASKA_SEED_OFFICE_PASSWORD"] = office_password
    py = BACKEND / "venv" / "Scripts" / "python.exe"
    alembic = BACKEND / "venv" / "Scripts" / "alembic.exe"
    if not py.is_file():
        print("ERROR: backend venv python not found", file=sys.stderr)
        return 1
    if not alembic.is_file():
        print("ERROR: alembic not installed in venv — run: pip install -r requirements.txt", file=sys.stderr)
        return 1

    try:
        print("\n== check_production_env ==")
        subprocess.run([str(py), "scripts/check_production_env.py"], cwd=BACKEND, env=env, check=True)

        print("\n== alembic upgrade head ==")
        subprocess.run([str(alembic), "upgrade", "head"], cwd=BACKEND, env=env, check=True)

        if not args.skip_seed:
            print("\n== seed admin ==")
            subprocess.run(
                [
                    str(py),
                    "scripts/seed_admin.py",
                    "--email",
                    admin_email,
                    "--password",
                    admin_password,
                ],
                cwd=BACKEND,
                env=env,
                check=True,
            )
            print("\n== seed offices ==")
            subprocess.run([str(py), "scripts/seed_office_accounts.py"], cwd=BACKEND, env=env, check=True)
            subprocess.run([str(py), "scripts/seed_office_aliases.py"], cwd=BACKEND, env=env, check=True)
            print("\n== KB inspect / restore dry-run ==")
            subprocess.run([str(py), "scripts/inspect_kb_articles.py"], cwd=BACKEND, env=env, check=True)
            subprocess.run(
                [str(py), "scripts/restore_public_kb_articles.py"],
                cwd=BACKEND,
                env=env,
                check=True,
            )
    finally:
        if restore_daily and tmp_bak and tmp_bak.is_file():
            shutil.copy2(tmp_bak, daily_env)
            tmp_bak.unlink(missing_ok=True)
            print("Restored daily-dev backend/.env")

    print("\nDone.")
    print("Open deploy/BOOTSTRAP_CREDENTIALS.txt and store it somewhere safe.")
    print("Add hosts entry (Admin PowerShell):")
    print("  Add-Content $env:WINDIR\\System32\\drivers\\etc\\hosts '127.0.0.1 aska.local'")
    print("Campus VPS: replace certs with Lets Encrypt + real hostname, then https compose.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
